title: Öffnungsperspektive in fünf Schritten Flowchart
description: Flowchart Visualisierung des 'Öffnungsperspektive in fünf Schritten' Konzepts der Deutschen Bundesregierung
theme: jekyll-theme-cayman
